name: 'Jira OAuth Access Token'
description: 'Github Action used to retrieve a Jira OAuth access token from the Jira Authorization server '
inputs:
  client-id:
    description: 'jira oauth client id'
    required: true
  client-secret:
    description: 'jira oauth client secret'
    required: true
outputs:
  access-token:
    description: 'The access token retrieved from the Jira authorization server'
runs:
  using: 'node12'
  main: 'index.js'
